package com.waminiyi.realestatemanager.core.util.sync

import android.util.Log
import com.waminiyi.realestatemanager.core.data.datastore.model.LastCommit
import com.waminiyi.realestatemanager.core.data.remote.model.RemoteChange
import com.waminiyi.realestatemanager.core.model.data.DataResult
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine

/**
 * Interface marker for a class that manages synchronization between local data and a remote
 * source for a [Syncable].
 */
interface Synchronizer {
    suspend fun getLastLocalChangeCommit(): LastCommit

    suspend fun updateLocalChangeCommit(update: LastCommit.() -> LastCommit)

    /**
     * Syntactic sugar to call [Syncable.syncWith] while omitting the synchronizer argument
     */
    suspend fun Syncable.sync() = this@sync.syncWith(this@Synchronizer)
}

/**
 * Interface marker for a class that is synchronized with a remote source. Syncing must not be
 * performed concurrently and it is the [Synchronizer]'s responsibility to ensure this.
 */
interface Syncable {
    /**
     * Synchronizes the local database backing the repository with the network.
     * Returns if the sync was successful or not.
     */
    suspend fun syncWith(synchronizer: Synchronizer): Boolean
}

/**
 * Attempts [block], returning a successful [Result] if it succeeds, otherwise a [Result.Failure]
 * taking care not to break structured concurrency
 */
private suspend fun <T> suspendRunCatching(block: suspend () -> T): DataResult<T> = try {
    DataResult.Success(block())
} catch (cancellationException: CancellationException) {
    throw cancellationException
} catch (exception: Exception) {
    Log.i(
        "suspendRunCatching",
        "Failed to evaluate a suspendRunCatchingBlock. Returning failure Result",
        exception,
    )
    DataResult.Error(exception)
}

/**
 * Utility function for syncing a repository with the network.
 * [versionReader] Reads the current version of the model that needs to be synced
 * [changeListFetcher] Fetches the change list for the model
 * [versionUpdater] Updates the [LastCommit] after a successful sync
 * [modelDeleter] Deletes models by consuming the ids and the class tag of the models that have been deleted.
 * [modelUpdater] Updates models by consuming the ids and the class tag of the models that have changed.
 *
 * Note that the blocks defined above are never run concurrently, and the [Synchronizer]
 * implementation must guarantee this.
 */
suspend fun Synchronizer.changeListSync(
    versionReader: (LastCommit) -> Long,
    changeListFetcher: suspend (Long) -> Pair<Long, List<RemoteChange>>,
    versionUpdater: LastCommit.(Long) -> LastCommit,
    modelDeleter: suspend (List<Pair<String, String>>) -> Unit,
    modelUpdater: suspend (List<Pair<String, String>>) -> Unit,
) = suspendRunCatching {
    // Fetch the change list since last sync (akin to a git fetch)
    val currentVersion = versionReader(getLastLocalChangeCommit())
    val changeList = changeListFetcher(currentVersion)
    if (changeList.second.isEmpty()) return@suspendRunCatching true

    val (deleted, updated) = changeList.second.partition(RemoteChange::isDelete)

    // Delete models that have been deleted server-side
    modelDeleter(deleted.map { (it.id to it.tag) })

    // Using the change list, pull down and save the changes (akin to a git pull)
    modelUpdater(updated.map { (it.id to it.tag) })

    // Update the last synced version (akin to updating local git HEAD)
    val latestVersion = changeList.first
    updateLocalChangeCommit {
        versionUpdater(latestVersion)
    }
}.isSuccess

/**
 * Returns a [Flow] whose values are generated by [transform] function that process the most
 * recently emitted values by each flow.
 */
fun <T1, T2, T3, T4, T5, T6, R> combine(
    flow: Flow<T1>,
    flow2: Flow<T2>,
    flow3: Flow<T3>,
    flow4: Flow<T4>,
    flow5: Flow<T5>,
    flow6: Flow<T6>,
    transform: suspend (T1, T2, T3, T4, T5, T6) -> R,
): Flow<R> = combine(
    combine(flow, flow2, flow3, ::Triple),
    combine(flow4, flow5, flow6, ::Triple),
) { t1, t2 ->
    transform(
        t1.first,
        t1.second,
        t1.third,
        t2.first,
        t2.second,
        t2.third,
    )
}